version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: tam_data_pass
      POSTGRES_USER: tam_data
      POSTGRES_DB: velomagg